name: Publish API to NPM Registry

on: workflow_dispatch

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm run build
      - run: |
          cp package.json dist/package.json
          cp README.md dist/README.md
      - run: npm publish
        working-directory: ./api/dist
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

